### ISSUE TITLE
IDE1006 Naming rule violation: ложное срабатывание на public static полях

### ISSUE THREAD

**Issue by annchous** [kysect/CodeRules#24]
В editorconfig'е есть такие строчки:
`dotnet_naming_rule.public_protected_static_readonly_fields_must_be_pascal_case_rule.style      = pascal_case_style`
и
`dotnet_naming_rule.other_public_protected_fields_disallowed_rule.style               = disallowed_style`

Собственно, проблема в том, что с public static **readonly** полями всё работает (ошибок нет), а вот с просто public static полями летит ошибка:
![image](https://user-images.githubusercontent.com/57408376/189458811-19df4e95-ad17-4610-bf63-4361e34db91e.png)

И к ней предлагается забавный фикс:
![image](https://user-images.githubusercontent.com/57408376/189458846-3b3efded-4c37-43c5-8bfa-ba870f70b952.png)
![image](https://user-images.githubusercontent.com/57408376/189458863-7602df76-00c4-4558-a00f-bfec6249216d.png)

Если добавить `readonly` - то всё чинится. Проблема кроется в `disallowed style`, который не учитывает не readonly статические поля.

**Comment by FrediKats** [comment]
Больше не используется `dotnet_naming_rule`.
