### ISSUE TITLE
Написать шаблоны для создания проектов

### ISSUE THREAD

**Issue by ronimizy** [kysect/CodeRules#4]
## Задача
В .NET есть возможность делать шаблоны для создания `.csproj` проектов. В них можно указывать добавляемые туда атрибуты. Нужно сделать шаблон, добавляющий по умолчанию .editorconfig файл из корня солюшена к проекту при создании.

**Comment by FrediKats** [comment]
За время существования задачи было время переосмыслить понимание проектной структуры.

Большая часть конфигурации, которую хочется шаблонизировать, относиться ко всему солюшену, а не к отдельнрым проектам - атрибуты, .editorconfig etc. И делать специальные шаблоны проектов кажется не корректным способом решать проблему.

Но с другой стороны, можно выстроить воркфлоу так, чтобы .csproj не нужно было настраивать шаблонами - перенести конфигурацию на уровень солюшена. Для этого достаточно сделать шаблон репозитория, где будет лежать набор нужных файлов:
- .editorconfig
- Directory.Packages.props для поддержки CPM (https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management)
- Directory.Build.props с прописанными конфигурациями

В итоге в .csproj остаются TargetFramework и PackageReference.

Шаблон теперь лежит тут: https://github.com/kysect/Template
